name: Workgroup Pulse CI

on:
  push:
    branches: [main]
    paths:
      - 'apps/workgroup_pulse/**'
      - 'shared/**'
      - '.github/workflows/workgroup_pulse.yml'
      - '.github/workflows/_elixir-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'apps/workgroup_pulse/**'
      - 'shared/**'
      - '.github/workflows/workgroup_pulse.yml'
      - '.github/workflows/_elixir-ci.yml'

jobs:
  ci:
    uses: ./.github/workflows/_elixir-ci.yml
    with:
      app_name: wp
      app_path: apps/workgroup_pulse
      database_name: workgroup_pulse_test
      deploy_enabled: true
    secrets: inherit
