name: Workgroup Pulse CI

on:
  push:
    branches: [main]
    paths:
      - 'apps/workgroup_pulse/**'
      - 'apps/oostkit_shared/**'
      - 'shared/**'
      - '.github/workflows/workgroup_pulse.yml'
      - '.github/workflows/_elixir-ci.yml'
  pull_request:
    branches: [main]
    paths:
      - 'apps/workgroup_pulse/**'
      - 'apps/oostkit_shared/**'
      - 'shared/**'
      - '.github/workflows/workgroup_pulse.yml'
      - '.github/workflows/_elixir-ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/_elixir-ci.yml
    with:
      app_name: wp
      app_path: apps/workgroup_pulse
      database_name: workgroup_pulse_test
      deploy_enabled: true
      app_url: 'https://pulse.oostkit.com'
    secrets: inherit
